language: go
go: 1.9

install:
  - go get -v -t .
  - go get -v github.com/mattn/goveralls
  - go install -v github.com/mattn/goveralls

script:
  - go test . -covermode count -coverprofile cover.out
  - go test -test.run Benchmark -cpu 1 -bench ./...
  - go test ./bridge
  - go test ./html
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out

notifications:
  email: false