language: go

go:
  - 1.10.x

install:
  - go get -v -t .                                                                                        
  - go get -v github.com/mattn/goveralls
  - go get -v github.com/disintegration/imaging
  - go get -v github.com/segmentio/conf
  - go install -v github.com/mattn/goveralls

script:
  - go test . -covermode count -coverprofile cover.out
  - go test ./appjs
  - go test ./bridge
  - go test ./html
  - go test ./file
  - go build ./cmd/goapp                                                                                                                             
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out

notifications:
  email: false