---
language: go
go: 1.7

install:
  - go get -v -t .
  - go get -v github.com/mattn/goveralls
  - go install -v github.com/mattn/goveralls

script:
  - go test -covermode count -coverprofile cover.out
  - go test -test.run Benchmark -cpu 1 -bench .
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out

notifications:
  email: false