name: Build

on: [push]

jobs:
  code:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Vet
        run: go vet ./...

  server:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Unit Tests
        run: go test -race ./...

  client:
    name: WebAssembly Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install WASM Browser Test
        run: |
          go install github.com/agnivade/wasmbrowsertest@latest
          mv `go env GOPATH`/bin/wasmbrowsertest `go env GOPATH`/bin/go_js_wasm_exec
      - name: Run Unit Tests
        run: |
          GOARCH=wasm GOOS=js go test ./pkg/app
