name: Build

on: [push]

jobs:
  code:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Vet
        run: |
          go vet ./pkg/app
          go vet ./pkg/errors
          go vet ./pkg/logs
          go vet ./pkg/cache
          go vet ./pkg/cli

  server:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Unit Tests
        run: |
          go test -race ./pkg/app
          go test -race ./pkg/errors
          go test -race ./pkg/logs
          go test -race ./pkg/cache

  client:
    name: WebAssembly Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install WASM Browser Test
        run: |
          go install github.com/agnivade/wasmbrowsertest@latest
          mv `go env GOPATH`/bin/wasmbrowsertest `go env GOPATH`/bin/go_js_wasm_exec
      - name: Run Unit Tests
        run: |
          GOARCH=wasm GOOS=js GO_WASM_EXEC="$(go env GOPATH)/bin/go_js_wasm_exec --no-sandbox" go test ./pkg/app
          GOARCH=wasm GOOS=js GO_WASM_EXEC="$(go env GOPATH)/bin/go_js_wasm_exec --no-sandbox" go test ./pkg/errors
          GOARCH=wasm GOOS=js GO_WASM_EXEC="$(go env GOPATH)/bin/go_js_wasm_exec --no-sandbox" go test ./pkg/logs
